smtp:
  password: ${SMTP_PASSWORD:password}
  server: ${SMTP_SERVER:localhost}
  port: ${SMTP_PORT:465}
  username: ${SMTP_USERNAME:username}
server:
  error:
    whitelabel:
      enabled: 'false'
    include-stacktrace: never
    include-message: always
  url: ${SERVER_URL:localhost:8080}
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      enabled: 'true'
      max-request-size: 215MB
      file-size-threshold: 2KB
  liquibase:
    change-log: classpath:db-changelog.xml
  datasource:
    password: ${POSTGRES_PASSWORD:postgres}
    username: ${POSTGRES_USER:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost/postgres}
  jpa:
    hibernate:
      ddl-auto: validate
jwt:
  token:
    expire-length: '345600000'
    secret-key: ${JWT_SECRET:my-super-secret-jwt-key-that-no-one-knows}
appstorage:
  path: ${APP_STORAGE_PATH:./data}
